service: cognito-triggers-sls

projectDir: '../'

plugins:
  - serverless-offline

provider:
  iamRoleStatements:
    - Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Effect: Allow
      Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: dev
  versionFunctions: false
  timeout: 29
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  # environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 9998
    lambdaPort: 9997

functions:
  PostAuthentication_Authentication:
    handler: handler.PostAuthentication_Authentication

  PostConfirmation_ConfirmSignUp:
    handler: handler.PostConfirmation_ConfirmSignUp
