name: Node.js Client Integration Cognito Local

on:
  pull_request:

jobs:
  client_integration_cognito:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [1]
        ci_node_index: [0]
    env:
      CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      CI_NODE_INDEX: ${{ matrix.ci_node_index }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.10.2
          security-enabled: false
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          port: 8000
          cors: '*'
      - name: Install Node Dependencies
        run: npm ci && cd cognito-triggers-sls && npm ci
      - name: Cognito-Local Integration Tests
        run: |
          mkdir -p /tmp/web-client
          npm run start:api:cognito-local:ci > /tmp/web-client/server-output.txt &
          ./wait-until-services.sh
          export TESTFILES="web-client/integration-tests-cognito-local/*.test.ts"
          npm run test:client:integration:cognito-local:ci
      - name: Store Video Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server log output
          path: /tmp/web-client/server-output.txt
